#!/usr/bin/env zsh

export PERL5LIB=lib

IFS=','

checks="BSVG,Braunschweig,Hbf,Volkmarode,Moorhüttenweg
DING,Ulm,Hbf,Ulm,Theodor-Heuss-Platz
KVV,Karlsruhe,Hbf,Karlsruhe,Tivoli
LinzAG,Linz/Donau,Hbf,Linz/Donau,Hart
MVV,München,Donnersbergerbrücke,München,Seeholzenweg
NVBW,Stuttgart,Brendle (Großmarkt),Stuttgart,Kleinhohenheim
VAG,Schallstadt,Bf,Freiburg im Breisgau,Hbf
VGN,Nürnberg,Hbf,Nürnberg,Messe
VMV,Schwerin,Hbf,Schwerin,Dreescher Markt
VRN,Mannheim,Hbf,Ludwigshafen (Rhein),Hbf
VRR,Essen,Hbf,Essen,Rüttenscheider Stern
VRR2,Essen,Hbf,Essen,Rüttenscheider Stern
VRR3,Essen,Hbf,Essen,Rüttenscheider Stern
VVO,Dresden,Hbf,Dresden,Altmarkt
VVS,Stuttgart,Brendle (Großmarkt),Stuttgart,Schwabstraße"

echo $checks | while read service from_name from_place to_name to_place; do
	echo -n "${service} ... "
	if bin/efa -s $service $from_name $from_place $to_name $to_place > /dev/null; then
		echo OK
	fi
done
